package analyzer

import (
	"os"
	"path/filepath"
	"testing"
)

const (
	testDirPerm  = 0o755
	testFilePerm = 0o644
)

func TestAnalyzeReportsUnusedAndUnlistedDependencies(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "go.mod", `module example.com/app

go 1.25

require (
	github.com/used/mod v1.0.0
	github.com/unused/mod v1.0.0
)
`)
	writeFile(t, root, "main.go", `package main

import (
	_ "github.com/used/mod/pkg"
	_ "github.com/missing/mod/pkg"
	"fmt"
)

func main() { fmt.Println("ok") }
`)

	report, err := Analyze(Options{Root: root, IncludeTests: true, IncludeGenerated: true})
	if err != nil {
		t.Fatalf("Analyze() error = %v", err)
	}

	if got := report.Summary.UnusedDependencies; got != 1 {
		t.Fatalf("unused dependencies = %d; want 1", got)
	}
	if got := report.Summary.UnlistedDependencies; got != 1 {
		t.Fatalf("unlisted dependencies = %d; want 1", got)
	}

	assertFinding(t, report, FindingUnusedDependency, "github.com/unused/mod")
	assertFinding(t, report, FindingUnlistedDependency, "github.com/missing/mod/pkg")
}

func TestAnalyzeReportsTestOnlyDependency(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "go.mod", `module example.com/app

go 1.25

require github.com/test/mod v1.0.0
`)
	writeFile(t, root, "main.go", `package main

func main() {}
`)
	writeFile(t, root, "main_test.go", `package main

import _ "github.com/test/mod/assert"

func TestMain(t *testing.T) {}
`)

	report, err := Analyze(Options{Root: root, IncludeTests: true, IncludeGenerated: true})
	if err != nil {
		t.Fatalf("Analyze() error = %v", err)
	}
	if got := report.Summary.TestOnlyDependencies; got != 1 {
		t.Fatalf("test-only dependencies = %d; want 1", got)
	}

	productionReport, err := Analyze(Options{Root: root, IncludeTests: false, IncludeGenerated: true})
	if err != nil {
		t.Fatalf("Analyze() production error = %v", err)
	}
	if got := productionReport.Summary.UnusedDependencies; got != 1 {
		t.Fatalf("production unused dependencies = %d; want 1", got)
	}
}

func TestAnalyzeKeepsNestedModulesSeparate(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "go.mod", `module example.com/root

go 1.25

require github.com/child/only v1.0.0
`)
	writeFile(t, root, "main.go", `package main

func main() {}
`)
	writeFile(t, root, "child/go.mod", `module example.com/child

go 1.25

require github.com/child/only v1.0.0
`)
	writeFile(t, root, "child/child.go", `package child

import _ "github.com/child/only/pkg"
`)

	report, err := Analyze(Options{Root: root, IncludeTests: true, IncludeGenerated: true})
	if err != nil {
		t.Fatalf("Analyze() error = %v", err)
	}
	if got := report.Summary.Modules; got != 2 {
		t.Fatalf("modules = %d; want 2", got)
	}
	if got := report.Summary.UnusedDependencies; got != 1 {
		t.Fatalf("unused dependencies = %d; want 1", got)
	}

	rootFinding := report.Modules[0].Findings[0]
	if len(rootFinding.UsedInModules) != 1 || rootFinding.UsedInModules[0] != "child" {
		t.Fatalf("UsedInModules = %v; want [child]", rootFinding.UsedInModules)
	}
}

func TestAnalyzeCanIgnoreGeneratedFiles(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "go.mod", `module example.com/app

go 1.25

require github.com/generated/mod v1.0.0
`)
	writeFile(t, root, "generated.go", `// Code generated by fixture. DO NOT EDIT.

package main

import _ "github.com/generated/mod/pkg"
`)

	report, err := Analyze(Options{Root: root, IncludeTests: true, IncludeGenerated: false})
	if err != nil {
		t.Fatalf("Analyze() error = %v", err)
	}
	if got := report.Summary.UnusedDependencies; got != 1 {
		t.Fatalf("unused dependencies = %d; want 1", got)
	}
}

func TestAnalyzeReportsUnusedPackageAndFile(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "go.mod", `module example.com/app

go 1.25
`)
	writeFile(t, root, "main.go", `package main

import "example.com/app/live"

func main() { live.Used() }
`)
	writeFile(t, root, "live/used.go", `package live

func Used() {}
`)
	writeFile(t, root, "live/dead.go", `package live

func Extra() {}
`)
	writeFile(t, root, "dead/dead.go", `package dead

func Dead() {}
`)

	report, err := Analyze(Options{Root: root, IncludeTests: true, IncludeGenerated: true})
	if err != nil {
		t.Fatalf("Analyze() error = %v", err)
	}

	if got := report.Summary.UnusedPackages; got != 1 {
		t.Fatalf("unused packages = %d; want 1", got)
	}
	if got := report.Summary.UnusedFiles; got != 1 {
		t.Fatalf("unused files = %d; want 1", got)
	}
	if got := report.Summary.UnusedFunctions; got != 1 {
		t.Fatalf("unused functions = %d; want 1", got)
	}

	assertFinding(t, report, FindingUnusedPackage, "example.com/app/dead")
	assertSymbolFinding(t, report, FindingUnusedFunction, "Extra")
}

func TestAnalyzeReportsUnusedSymbols(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "go.mod", `module example.com/app

go 1.25
`)
	writeFile(t, root, "main.go", `package main

import "example.com/app/lib"

func main() { lib.Used() }
`)
	writeFile(t, root, "lib/lib.go", "package lib\n\n"+
		"type LiveStruct struct {\n"+
		"\tUsedField int\n"+
		"\tDeadField int\n"+
		"\tTagged string `json:\"tagged\"`\n"+
		"}\n\n"+
		"func Used() {\n"+
		"\tvalue := LiveStruct{UsedField: 1}\n"+
		"\t_ = value.UsedMethod()\n"+
		"}\n\n"+
		"func Dead() {}\n\n"+
		"func (LiveStruct) UsedMethod() int { return 0 }\n\n"+
		"func (LiveStruct) DeadMethod() {}\n\n"+
		"type DeadStruct struct{}\n")

	report, err := Analyze(Options{Root: root, IncludeTests: true, IncludeGenerated: true})
	if err != nil {
		t.Fatalf("Analyze() error = %v", err)
	}

	if got := report.Summary.UnusedFunctions; got != 1 {
		t.Fatalf("unused functions = %d; want 1", got)
	}
	if got := report.Summary.UnusedMethods; got != 1 {
		t.Fatalf("unused methods = %d; want 1", got)
	}
	if got := report.Summary.UnusedStructs; got != 1 {
		t.Fatalf("unused structs = %d; want 1", got)
	}
	if got := report.Summary.UnusedFields; got != 1 {
		t.Fatalf("unused fields = %d; want 1", got)
	}

	assertSymbolFinding(t, report, FindingUnusedFunction, "Dead")
	assertSymbolFinding(t, report, FindingUnusedMethod, "DeadMethod")
	assertSymbolFinding(t, report, FindingUnusedStruct, "DeadStruct")
	assertSymbolFinding(t, report, FindingUnusedField, "DeadField")
	assertNoSymbolFinding(t, report, FindingUnusedField, "Tagged")
}

func TestAnalyzeTreatsDecodedStructFieldsAsUsed(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "go.mod", `module example.com/app

go 1.25
`)
	writeFile(t, root, "main.go", `package main

type layout struct {
	UsedByDecode int
	Nested nestedLayout
}

type nestedLayout struct {
	UsedByParentDecode int
}

type decoder struct{}

func (decoder) Decode(v any) error { return nil }

func main() {
	var value layout
	_ = decoder{}.Decode(&value)
}
`)
	writeFile(t, root, "chain.go", `package main

import bin "example.com/bin"

type chainLayout struct {
	UsedByDecodeChain int
}

func decodeChain() error {
	var value chainLayout
	if err := bin.NewDecoder(nil).Decode(&value); err != nil {
		return err
	}
	return nil
}
`)

	report, err := Analyze(Options{Root: root, IncludeTests: true, IncludeGenerated: true})
	if err != nil {
		t.Fatalf("Analyze() error = %v", err)
	}

	if got := report.Summary.UnusedFields; got != 0 {
		t.Fatalf("unused fields = %d; want 0", got)
	}
}

func TestAnalyzeUsesTypesForSameNameMethods(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "go.mod", `module example.com/app

go 1.25
`)
	writeFile(t, root, "main.go", `package main

type live struct{}
type dead struct{}

func main() {
	var value live
	value.Touch()
}

func (live) Touch() {}
func (dead) Touch() {}
`)

	report, err := Analyze(Options{Root: root, IncludeTests: true, IncludeGenerated: true})
	if err != nil {
		t.Fatalf("Analyze() error = %v", err)
	}

	if got := report.Summary.UnusedMethods; got != 1 {
		t.Fatalf("unused methods = %d; want 1", got)
	}
	assertSymbolFinding(t, report, FindingUnusedMethod, "Touch")
}

func TestAnalyzeUsesTypesForSameNameFields(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "go.mod", `module example.com/app

go 1.25
`)
	writeFile(t, root, "main.go", `package main

type live struct {
	Value int
}

type dead struct {
	Value int
}

func main() {
	_ = live{Value: 1}
	var _ dead
}
`)

	report, err := Analyze(Options{Root: root, IncludeTests: true, IncludeGenerated: true})
	if err != nil {
		t.Fatalf("Analyze() error = %v", err)
	}

	if got := report.Summary.UnusedFields; got != 1 {
		t.Fatalf("unused fields = %d; want 1", got)
	}
	assertSymbolFinding(t, report, FindingUnusedField, "Value")
}

func TestAnalyzeUsesTypesForInterfaceImplementations(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "go.mod", `module example.com/app

go 1.25
`)
	writeFile(t, root, "main.go", `package main

type runner interface {
	Run()
}

type implementation struct{}

func main() {
	var _ runner = implementation{}
}

func (implementation) Run() {}
`)

	report, err := Analyze(Options{Root: root, IncludeTests: true, IncludeGenerated: true})
	if err != nil {
		t.Fatalf("Analyze() error = %v", err)
	}

	assertNoSymbolFinding(t, report, FindingUnusedMethod, "Run")
}

func TestAnalyzeUsesTypesForErrorImplementations(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "go.mod", `module example.com/app

go 1.25
`)
	writeFile(t, root, "main.go", `package main

type customError struct{}

func main() {
	_ = makeError()
}

func makeError() error { return customError{} }

func (customError) Error() string { return "custom" }
`)

	report, err := Analyze(Options{Root: root, IncludeTests: true, IncludeGenerated: true})
	if err != nil {
		t.Fatalf("Analyze() error = %v", err)
	}

	assertNoSymbolFinding(t, report, FindingUnusedMethod, "Error")
}

func TestAnalyzeAppliesRuleConfig(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "go.mod", `module example.com/app

go 1.25
`)
	writeFile(t, root, "main.go", `package main

func main() {}

func Dead() {}
`)

	report, err := Analyze(Options{
		Root:             root,
		IncludeTests:     true,
		IncludeGenerated: true,
		Rules:            map[string]string{FindingUnusedFunction: ruleOffSeverity},
	})
	if err != nil {
		t.Fatalf("Analyze() error = %v", err)
	}
	if got := report.Summary.UnusedFunctions; got != 0 {
		t.Fatalf("unused functions = %d; want 0", got)
	}
}

func TestAnalyzeAppliesIgnorePatterns(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "go.mod", `module example.com/app

go 1.25
`)
	writeFile(t, root, "ignored/dead.go", `package ignored

func Dead() {}
`)

	report, err := Analyze(Options{
		Root:             root,
		IncludeTests:     true,
		IncludeGenerated: true,
		IgnorePatterns:   []string{"ignored/**"},
	})
	if err != nil {
		t.Fatalf("Analyze() error = %v", err)
	}
	if got := report.Summary.Findings; got != 0 {
		t.Fatalf("findings = %d; want 0", got)
	}
}

func assertFinding(t *testing.T, report *Report, findingType string, value string) {
	t.Helper()

	for _, module := range report.Modules {
		for _, finding := range module.Findings {
			if finding.Type != findingType {
				continue
			}
			if finding.Module == value || finding.ImportPath == value {
				return
			}
		}
	}

	t.Fatalf("finding %s %q not found in %#v", findingType, value, report.Modules)
}

func assertSymbolFinding(t *testing.T, report *Report, findingType string, symbol string) {
	t.Helper()

	for _, module := range report.Modules {
		for _, finding := range module.Findings {
			if finding.Type == findingType && finding.Symbol == symbol {
				return
			}
		}
	}

	t.Fatalf("finding %s symbol %q not found in %#v", findingType, symbol, report.Modules)
}

func assertNoSymbolFinding(t *testing.T, report *Report, findingType string, symbol string) {
	t.Helper()

	for _, module := range report.Modules {
		for _, finding := range module.Findings {
			if finding.Type == findingType && finding.Symbol == symbol {
				t.Fatalf("unexpected finding %s symbol %q in %#v", findingType, symbol, report.Modules)
			}
		}
	}
}

func writeFile(t *testing.T, root string, name string, content string) {
	t.Helper()

	path := filepath.Join(root, name)
	if err := os.MkdirAll(filepath.Dir(path), testDirPerm); err != nil {
		t.Fatalf("MkdirAll() error = %v", err)
	}
	if err := os.WriteFile(path, []byte(content), testFilePerm); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}
}
